# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Team.create(code: 'CHI', city: 'Chicago', name: 'Blackhawks', logo: 'CHI.png')
Team.create(code: 'CBJ', city: 'Columbus', name: 'Blue Jackets', logo: 'CBJ.png')
Team.create(code: 'DET', city: 'Detroit', name: 'Red Wings', logo: 'DET.png')
Team.create(code: 'NSH', city: 'Nashville', name: 'Predators', logo: 'NSH.png')
Team.create(code: 'STL', city: 'St. Louis', name: 'Blues', logo: 'STL.png')
Team.create(code: 'NJ', city: 'New Jersey', name: 'Devils', logo: 'NJ.png')
Team.create(code: 'NYI', city: 'New York', name: 'Islanders', logo: 'NYI.png')
Team.create(code: 'NYR', city: 'New York', name: 'Rangers', logo: 'NYR.png')
Team.create(code: 'PHI', city: 'Philadelphia', name: 'Flyers', logo: 'PHI.png')
Team.create(code: 'PIT', city: 'Pittsburgh', name: 'Penguins', logo: 'PIT.png')
Team.create(code: 'CGY', city: 'Calgary', name: 'Flames', logo: 'CGY.png')
Team.create(code: 'COL', city: 'Colorado', name: 'Avalanche', logo: 'COL.png')
Team.create(code: 'EDM', city: 'Edmonton', name: 'Oilers', logo: 'EDM.png')
Team.create(code: 'MIN', city: 'Minnesota', name: 'Wild', logo: 'MIN.png')
Team.create(code: 'VAN', city: 'Vancouver', name: 'Canucks', logo: 'VAN.png')
Team.create(code: 'BOS', city: 'Boston', name: 'Bruins', logo: 'BOS.png')
Team.create(code: 'BUF', city: 'Buffalo', name: 'Sabres', logo: 'BUF.png')
Team.create(code: 'MTL', city: 'Montreal', name: 'Canadiens', logo: 'MTL.png')
Team.create(code: 'OTT', city: 'Ottawa', name: 'Senators', logo: 'OTT.png')
Team.create(code: 'TOR', city: 'Toronto', name: 'Maple Leafs', logo: 'TOR.png')
Team.create(code: 'ANA', city: 'Anaheim', name: 'Ducks', logo: 'ANA.png')
Team.create(code: 'DAL', city: 'Dallas', name: 'Stars', logo: 'DAL.png')
Team.create(code: 'LA', city: 'Los Angeles', name: 'Kings', logo: 'LA.png')
Team.create(code: 'PHX', city: 'Phoenix', name: 'Coyotes', logo: 'PHX.png')
Team.create(code: 'SJ', city: 'San Jose', name: 'Sharks', logo: 'SJ.png')
Team.create(code: 'CAR', city: 'Carolina', name: 'Hurricanes', logo: 'CAR.png')
Team.create(code: 'FLA', city: 'Florida', name: 'Panthers', logo: 'FLA.png')
Team.create(code: 'TB', city: 'Tampa Bay', name: 'Lightning', logo: 'TB.png')
Team.create(code: 'WSH', city: 'Washington', name: 'Capitals', logo: 'WSH.png')
Team.create(code: 'WPG', city: 'Winnipeg', name: 'Jets', logo: 'WPG.png')
